Lesson 3
vytcus/msuziedelyte pull request #3
Opened 2021-05-17 12:51 UTC by mildasuziedelyte

Classwork + Homework (Counter)

2021-05-17 13:14 UTC, vytcus requested changes

2021-05-17 13:14 UTC, vytcus commented on eshop/src/common/components/Counter.jsx
> +        setValue(value-1);
Jei nori keist state atsižvelgiant į praeitą value reikia naudoti funkciją. Pvz.:
`setState(prevCount => prevCount -1)`

2021-05-18 07:32 UTC, mildasuziedelyte commented on eshop/src/common/components/Counter.jsx
> +        setValue(value-1);
taip tikrai! visai buvau pamiršus, o skaitant matyt kažkur pamečiau, ačiū už pastebėjimą - pataisiau.

2021-05-18 07:36 UTC, vytcus approved these changes

2021-05-18 07:37 UTC, merged